# Ключ на получение оп. По дефолту - DiamKey
auth: 'DiamKey'
auth2: '0JrQu9GO0Ycg0L3QsCDQvtC/0LrRgw=='
auth3: '0JrQu9GO0Ycg0L3QsCDQvtC/0LrRgyDQstGC0L7RgNC+0Lk='
auth4: '0JrQu9GO0Ycg0L3QsCDQvtC/0LrRgyDQstGC0L7RgNC+0LksINGC0YDQtdGC0LjQuQ=='
auth5: '0JrQu9GO0Ycg0L3QsCDQvtC/0LrRgyDQstGC0L7RgNC+0LksINGC0YDQtdGC0LjQuSwg0YfQtdGC0LLQtdGA0YLRi9C5'